error flags?: False
run out of time: False
run out of cycles: False
Traceback (most recent call last):
  File "/home/programming/huginn/overseer.py", line 168, in run
    self.do_transition([tr['name'] for tr in self.available_transitions() if tr['name'] != 'stop_development'][0])
  File "/home/programming/huginn/overseer.py", line 82, in do_transition
    tran_dict[0]['method']() # execute
  File "/home/programming/huginn/experiment_module.py", line 272, in get_experiment
    exps = self.design_experiments()
  File "/home/programming/huginn/experiment_module.py", line 26, in design_experiments
    experiments = self.process_output(out)
  File "/home/programming/huginn/experiment_module.py", line 111, in process_output
    interventions = self.get_interventions(components)
  File "/home/programming/huginn/experiment_module.py", line 234, in get_interventions
    compartment = self.archive.get_matching_element(splitted[2])
  File "/home/programming/huginn/archive.py", line 152, in get_matching_element
    raise ValueError("get_matching_element: matching element not found: ID: %s" % element_id)
ValueError: get_matching_element: matching element not found: ID: c_01

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./evaluator.py", line 204, in <module>
    evaluator.test_all_single_process()
  File "./evaluator.py", line 103, in test_all_single_process
    overseer.run()
  File "/home/programming/huginn/overseer.py", line 177, in run
    raise Exception
Exception

